version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5000:80

  nginx-service:
    image: nginx
    volumes:
      - C:\Users\Hot\Documents\GitHub\Eksamen\nginx.conf
      
  postgres-service:
    image: postgres
    ports:
      - 5001:80
